name: portfolio-deploy

on: 
  push: 
    branches: 
      - main
  workflow_dispatch:

permissions:
      contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Vue
    
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: 'master'


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install and Build 
        run: |
          npm ci
          npm run build

      - name: Deploy to tleeaf.github.io
        env:
          SUPER_SECRET: ${{ secrets.MY_PAT }}
        id: deployment
        run: |
          cd dist
          git init
          git config user.name "Github Actions"
          git config user.email "<>"
         
          git add .
          git commit -m "Deploy from repository"
          git remote add origin https://github.com/tleeaf/tleeaf.github.io.git
          git remote set-url --push origin  https://x-access-token:$SUPER_SECRET@github.com/tleeaf/tleeaf.github.io.git
          git push origin master
