name: portfolio-deploy

on: 
  push: 
    branches: 
      - main
  workflow_dispatch:

permissions:
      contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Vue
    
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: 'master'
          

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install and Build 
        run: |
          npm ci
          npm run build

      - name: Deploy to tleeaf.github.io
        env:
          SUPER_SECRET: ${{ secrets.MY_PAT }}
        id: deployment
        run: |
          cd dist
          git init
          git config user.name "tleeaf"
          git config user.email "thomas.lee@uconn.edu"
          git add .
          git commit -m "Deploy from repository"
          git push --force git@github.com:tleeaf/tleeaf.github.io.git master
        
      
