name: portfolio-deploy

on: 
  push: 
    branches: 
      - main
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Vue
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ref: 'master'
          

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          
      - name: Install and Build 
        run: |
          npm ci
          npm run build

      - name: Deploy to tleeaf.github.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        id: deployment
        run: |
          cd dist
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy from repository"
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/tleeaf/tleeaf.github.io" master
        
      
